apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
    tier: prom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: prom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: prom
    spec:
      containers:
      - image: vimal13/prometheus
        name: prom
        ports:
        - containerPort: 9090
          name: prom
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/lib/prometheus
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pv-claim
